# Generated by Django 4.2 on 2024-09-18 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Введите количество ингредиента.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество ингредиента'),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
