# Generated by Django 4.2 on 2024-09-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_alter_recipeingredient_amount_delete_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'Граммы'), ('kg', 'Килограммы'), ('ml', 'Миллилитры'), ('l', 'Литры'), ('pcs', 'Штуки')], max_length=3, verbose_name='Единица измерения'),
        ),
    ]
