# Generated by Django 4.2 on 2024-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
