# Generated by Django 4.2 on 2024-09-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_avatar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='photo',
            new_name='avatar',
        ),
    ]
